# -*- coding: utf-8 -*-

import challenges
import random

from gettext import gettext as _

class ChallengesCreator:
    
    def __init__(self, container, rect, frame_rate, windows_controller, game_man, bg_color=(0, 0, 0)):
             
        # Windows attributes
        self.container = container
        self.rect = rect
        self.frame_rate = frame_rate
        self.windows_controller = windows_controller
        self.bg_color = bg_color

        self.game_man = game_man
        
        # Multiple Choice and Master window
        self.mc_challenge = challenges.MultipleChoice(self.container, self.rect, self.frame_rate, self.windows_controller, self, "mc_challenge_window", self.bg_color)
        
        # True or False window
        self.tf_challenge = challenges.TrueOrFalse(self.container, self.rect, self.frame_rate, self.windows_controller, self, "tf_challenge_window", self.bg_color)
        
        # Cooking window
        #self.cooking_challenge = challenges.Cooking(self.container, self.rect, self.frame_rate, self.windows_controller, "cooking_challenge_window", self.bg_color)
        
        # Tuples of mc_challenges
        self.mc_challenges = {}
        
        # Dict of true or false tuples
        self.tf_challenges = {}
        
        
    def create_challenges(self):
        # Common multiple choice
        
        """
        self._create_mc_challenge(_("Which foods do we need to eat every day?"), [_("Some food from each group every day"), _("Some fruits and vegetables only"), _("Some food from all the groups but not fats and sugar"), _("Some food from each group every day"), _("Some food from each group every day"), _("Some food from all the groups but not fats and sugar"), _("Some food from each group every day"), _("Some food from each group every day")], _("Some food from each group every day"), 10, 10)
        self._create_mc_challenge(_("What is the most important meal of the day?"), [_("Breakfast"), _("Lunch"), _("Tea"), _("Dinner"), _("Dinner"), _("Dinner")], _("Breakfast"), 10, 10)
        self._create_mc_challenge(_("How regularly should children exercise?"), [_("Once a day"), _("Once a month"), _("Once a week"), _("Once a day"), _("Once a day"), _("Once a day")], _("Once a day"), 10, 10)
        self._create_mc_challenge(_("What percentage of the body is made up of water?"), ["70%", "30%", "90%", "90%", "90%", "90%"], "70%", 10, 10)
        """
        
        ########################### Load challenges ###########################
        self.mc_challenges["physica"] = [
            self._create_mc_challenge(u"La actividad física se debe realizar:", [u"Todos los días por lo menos durante 30 minutos.", u"Una vez a la semana.", u"Dos veces en la semana.", u"Cientos de veces en la semana.", u"Una vez al mes.", u"Cinco veces al mes."], u"Todos los días por lo menos durante 30 minutos.", 1),
            self._create_mc_challenge(u"¿Cuáles de estas acciones sería una actividad física recomendada?", [u"Bailar.", u"Leer.", u"Comer.", u"Mirar TV.", u"Jugar con la XO.", u"Dormir."], u"Bailar.", 1),
            self._create_mc_challenge(u"Cuando vamos a realizar actividad física:", [u"Es importante llevar agua.", u"Debemos realizar actividad física al sol durante los horarios no permitidos por el MSP.", u"No debemos usar gorro si estamos al sol.", u"No es importante realizarnos controles médicos antes de realizar actividad física.", u"No es importante estirar nuestros músculos al realizar actividad física.", u"Las personas que padecieron un infarto al corazón no deben realizar actividad física."], u"Es importante llevar agua.", 1),
            self._create_mc_challenge(u"La actividad física: ", [u"Nos ayuda a prevenir enfermedades como por ejemplo obesidad, hipertensión arterial y diabetes.", u"No previene la osteoporosis.", u"No nos permite interactuar y conocer otros compañeros.", u"Solo debe ser realizada por personas delgadas.", u"No la pueden realizar obesos.", u"Solo los niños deben realizarla."], u"Nos ayuda a prevenir enfermedades como por ejemplo obesidad, hipertensión arterial y diabetes.", 2),
            self._create_mc_challenge(u"La actividad física:", [u"Disminuye el estrés.", u"No mejora nuestra digestión.", u"No nos ayuda a descansar mejor y tener un sueño adecuado.", u"No mejora nuestra imagen personal.", u"No nos ayuda a prevenir enfermedades como  por ejemplo obesidad, hipertensión arterial diabetes.", u"No previene la osteoporosis."], u"Disminuye el estrés.", 2),
            self._create_mc_challenge(u"El sedentarismo es:", [u"Un factor de riesgo para enfermedades cardiovasculares.", u"Realizar actividad física todos los días durante al menos 30 min.  ", u"Una enfermedad contagiosa.", u"Una fruta.", u"Una comida.", u"El título de un libro."], u"Un factor de riesgo para enfermedades cardiovasculares.", 3),
            self._create_mc_challenge(u"Acerca de la actividad física:", [u"Todas las veces que hagamos actividad física es muy importante tomar abundante agua para hidratarnos.", u"Antes de realizar actividad física no necesito controlarme con el doctor.", u"Es conveniente, para evitar el sedentarismo, pasar más de tres horas diarias sentados frente a la TV, la computadora, o el video juegos.", u"Bailar no es una actividad física.", u"La actividad física solo pueden realizarla adultos.", u"Solo tiene que realizar actividad física los escolares."], u"Todas las veces que hagamos actividad física es muy importante tomar abundante agua para hidratarnos.", 3),
            self._create_mc_challenge(u"Acerca de la actividad física:", [u"Se dice que una persona es sedentaria cuando su actividad física no llega a ser de por lo menos media hora diaria por lo menos 5 días a la semana.", u"Las personas que tuvieron un infarto no puede hacer actividad física.", u"Realizar actividad física solo es correr y jugar pelota y no otras actividades como bailar, o andar a caballo.", u"Para no ser sedentarios debemos hacer actividad física de moderada intensidad por lo menos 2 días a la semana con una duración de 10  min por día.", u"La gran mayoría de las personas  no deben realizar actividad física para mantenerse sanos.", u"Solo debe realizar actividad física si tengo sobrepeso."], u"Se dice que una persona es sedentaria cuando su actividad física no llega a ser de por lo menos media hora diaria por lo menos 5 días a la semana.", 4),
            self._create_mc_challenge(u"La  actividad física:", [u"Mejora nuestra salud cardiovascular.", u"No importa tomar agua cuando realizamos actividad física.", u"Nos hace subir de peso.", u"Solo la deben realizar los adultos.", u"Es menos importante que una buena alimentación.", u"Cuando realizamos actividad física  debemos ingerir coca cola."], u"Mejora nuestra salud cardiovascular.", 5),
            self._create_mc_challenge(u"¿Cual se estas preguntas acerca de actividad física te parece la correcta?", [u"El 40 % de los niños en Uruguay son sedentarios.", u"Es recomendable que estemos jugando en la Xo o mirando tv 5 horas por día.", u"Las personas son sedentarias cuando realizan actividad física 5 veces a la semana.", u"Los niños no necesitan realizar actividad física.", u"No es importante estirar nuestros músculos cuando hacemos actividad física.", u"Cuando realizamos actividad física no debemos ingerir agua."], u"El 40 % de los niños en Uruguay son sedentarios.", 5),
            self._create_mc_challenge(u"Acerca de la actividad física, elije la opción verdadera.", [u"Si realizamos actividad física desde niños podemos prevenir enfermedades cuando seamos más grandes.", u"Las personas que tienen enfermedades cardiovasculares no pueden hacer ningún tipo de actividad física.", u"Los niños  pequeños no necesitan hacer actividad física.", u"Los niños que realizan actividad física tienen más probabilidad de enfermarse.", u"Los adultos no tienen que realizar actividad física porque les perjudica su salud.", u"La actividad física solo deben realizarla las personas obesas."], u"Si realizamos actividad física desde niños podemos prevenir enfermedades cuando seamos más grandes.", 6),
            self._create_mc_challenge(u"La actividad física:", [u"Propicia una buena circulación a todos nuestro organismo.", u"No nos ayuda a controlar nuestro peso corporal.", u"No mejora la actividad de nuestro corazón.", u"No disminuye el estrés y libera tensiones.", u"No mejora nuestra digestión.", u"No mejora nuestra imagen personal."], u"Propicia una buena circulación a todos nuestro organismo.", 7),
            self._create_mc_challenge(u"Acerca de nuestras defensas del cuerpo:", [u"Las vacunas nos protegen de enfermedades y trabajan con nuestro sistema inmunológico. ", u"Las vacunas no son importantes para cuidar de nuestra salud.", u"Tener las vacunas al día no es importante.", u"El reír, descansar y disfrutar no afecta nuestro sistema inmunológico.", u"Si no nos alimentamos correctamente nuestro sistema inmunológico no se afecta.", u"Las vacunas obligatorias no son gratuitas."], u"Las vacunas nos protegen de enfermedades y trabajan con nuestro sistema inmunológico. ", 8),
            self._create_mc_challenge(u"Acerca de nuestras defensas del cuerpo:", [u"Una mala alimentación puede afectar nuestras defensas y podemos enfermar.", u"Una buena alimentación no es importante para proteger nuestro sistema inmune.", u"Las vacunas no nos protegen de enfermedades.", u"No es importante revisar mi carné de vacunas.", u"Solo los ancianos deben vacunarse.", u"Si no descansamos nuestro sistema inmune puede verse afectado."], u"Una mala alimentación puede afectar nuestras defensas y podemos enfermar.", 9),
            self._create_mc_challenge(u"Acerca de nuestras defensas :", [u"El reír, el  descansar, y el alimentarnos saludablemente aumenta nuestras defensas.", u"Debemos comer pocas frutas y verduras para aumentar nuestras defensas. ", u"Descansar y dormir poco aumenta nuestras defensas.", u"Tomar mate unicamente aumenta nuestras defensas.", u"Estar todo el día sin hacer nada aumenta nuestras las defensas.", u"El sedentarismo es muy bueno para aumentar nuestras defensas."], u"El reír, el  descansar, y el alimentarnos saludablemente aumenta nuestras defensas.", 1),
            self._create_mc_challenge(u"Acerca de las defensas de nuestro organismo:", [u"Son una barrera  que ayudan a que no nos enfermemos", u"Son un cuadro de fútbol.", u"No son importantes.", u"No ayudan a defendernos de las enfermedades.", u"Es el nombre de un libro de cuentos.", u"Son un grupo de amigos."], u"Son una barrera  que ayudan a que no nos enfermemos", 1),
            self._create_mc_challenge(u"Acerca del sobrepeso:", [u"Es un factor de riesgo para padecer enfermedades cardiovasculares. ", u"Es muy saludable tener sobrepeso", u"Todos los niños deben tener sobre peso.", u"Consumir muchas grasas no nos predispone a tener sobrepeso.", u"Todos los niños deben tener sobrepeso.", u"Si tengo sobrepeso no voy a tener problemas cardiovasculares."], u"Es un factor de riesgo para padecer enfermedades cardiovasculares. ", 1),
            self._create_mc_challenge(u"Si estoy demasiado delgado:", [u" Pueden afectarse nuestras defensas", u"Nuestras defensas aumentan", u"Nuestras fuerzas y energías aumentan.", u"Disminuye el riesgo de enfermar.", u"No es necesario consultar al doctor si estoy demasiado delgado.", u"El control de mi peso en mis control de mi peso en los controles en salud no es importante."], u" Pueden afectarse nuestras defensas", 1),
            self._create_mc_challenge(u"Las causas de sobrepeso pueden ser:", [u"Porque no realizo ejercicio ", u"Porque realizo ejercicio", u"Porque consumo frutas y verduras", u"Porque consumo muchas naranjas.", u"Porque practico deportes todos los días.", u"Porque consumo una dieta variada."], u"Porque no realizo ejercicio ", 1),
            self._create_mc_challenge(u"¿En Uruguay cuántos niños tienen sobrepeso?", [u"1 cada cuatro.", u"1 cada un millón.", u"La mitad de los niños del país.", u"3 millones de niños.", u"1 cada cien mil niños.", u"Todos los niños y niñas. "], u"1 cada cuatro.", 1),
            self._create_mc_challenge(u"El sedentarismo es :", [u"No realizar suficiente actividad física.", u"Jugar con con amigos y amigas.", u"Practicar deportes diariamente", u"Realizar actividades físicas que me gusten.", u"Caminar todos los días.", u"Una infección contagiosa."], u"No realizar suficiente actividad física.", 1)                     
        ]
        
        self.mc_challenges["hygiene"] = [
            self._create_mc_challenge(u"Acerca de la salud bucal:", [u"Los dientes deben cepillarse luego de cada comida.  ", u"Los dientes deben cepillarse sin pasta dental.", u"Lo dientes no deben cepillarse.", u"Los dientes deben cepillarse solo después que comí carne.", u"Solo se  deben cepillar los dientes si comí chicle.", u"Es muy recomendable comer golosinas y no cepillarse los dientes."], u"Los dientes deben cepillarse luego de cada comida.  ", 1),
            self._create_mc_challenge(u"Los niños y adolescentes deben cepillar sus dientes:", [u"Cada vez que consumen un alimento. ", u"Dos veces al día.", u"Tres veces al día.", u"Cinco veces al día.", u"Cuando vamos a realizar ejercicio.", u"Cuando vamos a nadar."], u"Cada vez que consumen un alimento. ", 1),
            self._create_mc_challenge(u"Para mantener una correcta higiene y estar saludable debo:", [u"Bañarme con agua y jabón todos los días.", u"Lavarme las manos después de comer.", u"Lavarme las manos únicamente para comer.", u"Bañarme con agua y jabón una vez a la semana.", u"Lavarme las manos sin agua y jabón.", u"Cepillar mis dientes una vez al día."], u"Bañarme con agua y jabón todos los días.", 1),
            self._create_mc_challenge(u"En relación a los hábitos higiénicos: ", [u"Antes de manipular los alimentos, prepararlos, y antes de consumirlos, debemos lavarnos las manos por lo menos durante 30 segundos. ", u"No es importante ducharnos todos los días. ", u"Cuando nos duchamos es importante que sea sin jabón.", u"Estando limpios no prevenimos enfermedades.", u"Los niños deben bañarse solo una vez a la semana. ", u"Los niños deben bañarse día por medio."], u"Antes de manipular los alimentos, prepararlos, y antes de consumirlos, debemos lavarnos las manos por lo menos durante 30 segundos. ", 1),
            self._create_mc_challenge(u"En relación al lavado de manos, indique cual es la oración correcta:", [u"El primer paso es mojarnos las manos con agua.", u"El primer paso es pasarnos jabón.", u"El alcohol en gel es mucho mejor que lavado con agua y jabón.", u"El lavado de manos no es una buena medida para prevenir enfermedades.", u"Solo en la escuela debo lavar mis manos.", u"Solo cuando voy al baño debo lavar mis manos."], u"El primer paso es mojarnos las manos con agua.", 1),
            self._create_mc_challenge(u"Acerca del lavado de manos, ¿qué opción es verdadera?", [u"El primer paso que debemos realizar es mojarnos las manos con agua.", u"El primer paso que debemos realizar es lavarnos las manos con agua sucia o estancada.", u"El primer paso que debemos realizar es colocar jabón en nuestras manos.", u"Si lavo mis manos no es importante lavar mis uñas.", u"Después de estornudar y sonar mi nariz no es  necesario lavar mis manos. ", u"El lavado de manos despues de tocar un animal no es importante.."], u"El primer paso que debemos realizar es mojarnos las manos con agua.", 1),
            self._create_mc_challenge(u"Es recomendable visitar el dentista:", [u"Una vez cada 6 meses.", u"Una vez cada 10 años.", u"Una vez cada 1 mes.", u"Una vez cada 2 días.", u"Una vez cada 5 años.", u"Una vez por semana."], u"Una vez cada 6 meses.", 1),
            self._create_mc_challenge(u"En relación al lavado de manos:", [u"Es muy importante enseñar a otros niños y a nuestras familias a lavarnos correctamente las manos.", u"Lavarnos las manos es menos importante que alimentarnos bien.", u"Debemos lavarnos las manos solo cuando sonamos nuestras narices.", u"El lavado de manos debe ser antes de sonar nuestras narices.", u"Las manos se lavan solo cuando las vemos sucias.", u"Las manos se lavan solo cuando vamos a comer."], u"Es muy importante enseñar a otros niños y a nuestras familias a lavarnos correctamente las manos.", 2),
            self._create_mc_challenge(u"Acerca de la salud bucal:", [u"Es recomendable visitar el dentista y ver cómo están mis dientes para prevenir enfermedades y aprender a cuidar mi salud bucal.", u"Los dientes sólo se cepillan si están sucios.", u"Los dientes de leche no se cepillan.", u"Solo los niños grandes  deben cepillar los dientes.", u"Los bebes no tienen que visitar al dentista.", u"Solo los adultos deben ir al dentista."], u"Es recomendable visitar el dentista y ver cómo están mis dientes para prevenir enfermedades y aprender a cuidar mi salud bucal.", 2),
            self._create_mc_challenge(u"Acerca de la salud bucal, marque la opción verdadera.", [u"El cepillado debe realizarse desde las encías hacia los dientes.", u"El cepillado debe realizarse desde los dientes hacia las encías.", u"El cepillado puede realizarse con los dedos.", u"Los alimentos ricos en azúcares no influyen en nuestra salud bucal.", u"Solo los dientes permanentes se cepillan, los de leche no es necesario que los cepille.", u"Si perdemos un diente con un traumatismo o golpe debemos tirarlo a la basura."], u"El cepillado debe realizarse desde las encías hacia los dientes.", 3),
            self._create_mc_challenge(u"Acerca de la salud bucal: ", [u"En la escuela se puede enseñar a los demás compañeros la técnica del cepillado de dientes para después entre todos enseñar en nuestra casa a los demás .", u"Tener mal aliento es agradable.", u"Tener dientes sanos y blancos no es agradable.", u"Los dientes no deben cepillarse siempre luego de cada comida.", u"No es importante enseñarle a los más pequeños en la escuela, como se cepillan los dientes.", u"No es importante enseñar a nuestra familia y amigos como cuidar de nuestra salud bucal."], u"En la escuela se puede enseñar a los demás compañeros la técnica del cepillado de dientes para después entre todos enseñar en nuestra casa a los demás .", 3),
            self._create_mc_challenge(u"Para evitar que se enfermen mis dientes es recomendable:", [u"Realizar controles con el odontólogo.", u"Comer muchas golosinas.", u"Fumar.", u"Cepillar mis dientes sólo cuando ingiero dulces.", u"Cepillar mis 10 veces al día.", u"Cepillar mis dientes una vez al día."], u"Realizar controles con el odontólogo.", 4),
            self._create_mc_challenge(u"Acerca de la salud bucal: ", [u"El mal aliento puede estar significando que mis dientes o encías están enfermos.", u"Solo deben cepillarse los dientes pero no las encías.", u"Solo deben cepillarse los dientes pero no la lengua.", u"Si no me duelen los dientes o las muelas no debo ir al dentista.", u"Los dientes no deben cepillarse.", u"Los dientes de leche no se deben cepillar."], u"El mal aliento puede estar significando que mis dientes o encías están enfermos.", 4),
            self._create_mc_challenge(u"En relación a la seguridad de los alimentos:", [u"La carne debe almacenarse en la heladera.  ", u"Cuando guardamos harinas o azúcares u otros alimentos debemos hacerlo en recipientes abiertos.", u"La carne debe dejarse al aire libre.", u"Los alimentos deben guardarse junto a productos químicos o venenos.", u"Los alimentos crudos se guardan junto a los cocidos en el mismo recipiente. ", u"Los huevos no deben almacenarse en la heladera."], u"La carne debe almacenarse en la heladera.  ", 5),
            self._create_mc_challenge(u"¿Qué conoces acerca de la salud bucal?", [u"Los alimentos ricos en calcio y flúor son muy  importantes para mis dientes.", u"Debo consumir muchos alimentos ricos en azúcares para cuidar mis dientes.", u"Los bebes no necesitan visitar al odontólogo.", u"Una alimentación variada rica en frutas y verduras no es importante para el cuidado de mis dientes.", u"Los dientes de leche no necesitan cepillarse.", u"Solo debo visitar al dentista cuando me duele algún diente."], u"Los alimentos ricos en calcio y flúor son muy  importantes para mis dientes.", 5),
            self._create_mc_challenge(u"Es recomendable que los controles con el dentista u odontólogo se realicen cada:", [u"6 meses  ", u"2 años", u"1 mes", u"15 días", u"6 años", u"10 años"], u"6 meses  ", 6),
            self._create_mc_challenge(u"En relación a la seguridad de los alimentos:", [u"Los alimentos como carnes y derivados deben colocarse en heladera lo más rápidamente luego de comprados. ", u"Lavar las  frutas y verduras solo si voy a consumirlas con cáscara.", u"No es necesario lavar frutas y verduras con agua e hipoclorito de sodio (cloro),. ", u"Es recomendable re-congelar o volver a congelar un alimento que ya fue descongelado. ", u"Si los vamos a descongelar podemos hacerlo directamente colocándolos a temperatura ambiente. ", u"Si tenemos mascotas no es importante mantenerlas lejos de nuestros alimentos. "], u"Los alimentos como carnes y derivados deben colocarse en heladera lo más rápidamente luego de comprados. ", 6),
            self._create_mc_challenge(u"En relación a la seguridad de los alimentos:", [u"No deberíamos consumir huevos poco cocidos, mayonesas caseras, o merengues crudos, por el peligro de padecer una enfermedad que se llama salmonelosis.", u"Cuando manipulamos carnes o huevos no es importante  lavar con agua caliente y jabón todos los utensilios de cocina que utilizamos.", u"Cuando guardamos harinas, fideos secos, azúcar debemos hacerlo en lugares abiertos al contacto de insectos y roedores.", u"La carne, fiambres, huevos, leche, manteca, deben ser almacenados a temperatura ambiente. ", u"Manipular los alimentos una forma higiénica no es muy importante para evitar la contaminación por microbios.  ", u""], u"No deberíamos consumir huevos poco cocidos, mayonesas caseras, o merengues crudos, por el peligro de padecer una enfermedad que se llama salmonelosis.", 7),
            self._create_mc_challenge(u"¿Cuál de estas preguntas es la verdadera?", [u"El habito de fumar afecta y perjudica seriamente nuestra salud bucal.", u"El habito de fuma no afecta nuestra salud bucal.", u"No es necesario cepillar los dientes de “leche”.", u"Es necesario cepillarse los dientes solo cuando consumimos dulces.", u"Los dientes deben cepillarse sin pasta de diente.", u"Mantener nuestros dientes sanos y fuerte son es importante."], u"El habito de fumar afecta y perjudica seriamente nuestra salud bucal.", 8),
            self._create_mc_challenge(u"¿Cuál de estas opciones te parece verdadera?", [u"La cáscara de las frutas son ricas en vitaminas. ", u"Las verduras deben lavarse con agua estancada y sin hipoclorito.", u"Las verduras no deben lavarse si las vamos a cocinar.", u"Se deben consumir todos los días frutas pero no verduras.", u"La cáscara de la fruta no es rica en vitaminas.", u"No es recomendable consumir frutas porque dañan nuestra salud."], u"La cáscara de las frutas son ricas en vitaminas. ", 9)                            
        ]
        
        self.mc_challenges["nutrition"] = [
            self._create_mc_challenge(u"¿Cuántas porciones de frutas y verduras deben consumirse diariamente?", [u"5", u"1", u"2", u"3", u"0", u"Media"], u"5", 1),
            self._create_mc_challenge(u"¿Cuántas porciones de carnes debo consumir diariamente?", [u"2 a 3 porciones diaria ", u"5 porciones diarias", u"1 porción diaria", u"7 porciones diarias", u"10 porciones diarias", u"4 porciones diarias"], u"2 a 3 porciones diaria ", 1),
            self._create_mc_challenge(u"¿Cuántas porciones de cereales y leguminosas se recomienda consumir diariamente?", [u"5 a 7 porciones diarias. ", u"10 porciones diarias.", u"7 galletas de campaña por día.", u"1 porción diaria.", u"2 porciones diarias.", u"8 porciones diarias."], u"5 a 7 porciones diarias. ", 1),
            self._create_mc_challenge(u"¿Cuántas porciones de lácteos, yogures o quesos se recomienda consumir diariamente?", [u"2 porciones diarias.", u"1 porción diaria.", u"5 porciones diarias.", u"10 porciones diarias.", u"Un litro de leche por día.", u"2 litros de yogurt por día."], u"2 porciones diarias.", 1),
            self._create_mc_challenge(u"¿Cuántas porciones de grasas y aceites deben consumirse diariamente?", [u"Entre 2 y 3.", u"10", u"11", u"7", u"8", u"5"], u"Entre 2 y 3.", 1),
            self._create_mc_challenge(u"¿Cuántas porciones de azúcares y dulces se recomienda consumir diariamente?", [u"4 y 5 porciones diarias.", u"1 porción diaria.", u"2 porciones diarias.", u"3 porciones diarias.", u"7 porciones diarias.", u"Media porción diaria."], u"4 y 5 porciones diarias.", 1),
            self._create_mc_challenge(u"Es muy saludable:", [u"Comer frutas y verduras todos los días.", u"Consumir grandes cantidades de grasas saturadas.", u"Consumir asado con mucha grasa.", u"Consumir mucha sal en los alimentos.", u"Consumir poca fruta y verdura.", u"No consumir leche o alimentos lácteos."], u"Comer frutas y verduras todos los días.", 1),
            self._create_mc_challenge(u"¿Qué alimentos contienen alto contenido de grasas?", [u"Algunos cortes de carnes.", u"Los cereales.", u"La manzana.", u"La frutilla.", u"Los quesos magros.", u"El pan integral."], u"Algunos cortes de carnes.", 1),
            self._create_mc_challenge(u"¿Cuál es la principal función de los hidratos de carbono?", [u"Nos aportan energía .", u"Nos permiten tener uñas y cabello fuertes.", u"Nos  oxigenan.", u"Nos otorgan anticuerpos.", u"Nos permiten absorber calcio.", u""], u"Nos aportan energía .", 1),
            self._create_mc_challenge(u"El grupo de las frutas y verduras comprende:", [u"Las naranjas.", u"Los alfajores.", u"El asado.", u"Las golosinas.", u"El helado.", u"El pan."], u"Las naranjas.", 1),
            self._create_mc_challenge(u"Las grasas saturadas:", [u"Se encuentran en varios cortes de carne de vaca. ", u"Se encuentran en las frutas.", u"No favorecen el desarrollo de ateroesclerosis.", u"Son muy buenas para la salud.", u"Aumentan los niveles de HDL o colesterol bueno.", u"Son el alimento ideal."], u"Se encuentran en varios cortes de carne de vaca. ", 2),
            self._create_mc_challenge(u"Consumir pocas grasas saturadas es importante porque:", [u"Puede provocarnos ateroesclerosis. ", u"Nos provoca diarrea.", u"Nos provoca  dolor de cabeza.", u"Nos provoca sed.", u"Nos provoca sueño.", u"Nos provoca sueño."], u"Puede provocarnos ateroesclerosis. ", 2),
            self._create_mc_challenge(u"El agua: ", [u"Regula nuestra temperatura corporal.", u"No permite el transporte de nutrientes a las células.", u"Los alimentos no contienen agua.", u"Las necesidades de agua varían entre 10 y 20 litros por día en las personas.", u"Cuando tenemos diarrea  no es importante tomar agua.", u"No es necesario lavar los alimentos con agua."], u"Regula nuestra temperatura corporal.", 2),
            self._create_mc_challenge(u"Acerca del consumo de sal: ", [u"Los alimentos naturalmente ya contienen sal, por eso se recomienda no abusar del agregado de sal o incluso no utilizar sal en los alimentos.", u"Solo los niños deben controlar su presión arterial.", u"Los adultos son los únicos que deben controlar su presión arterial.", u"Solo las personas hipertensas deben controlar su presión arterial.", u"Lo recomendable es consumir los alimentos con abundante cantidad de sal.", u"La toma de presión arterial en mis controles de salud  no es importarte. "], u"Los alimentos naturalmente ya contienen sal, por eso se recomienda no abusar del agregado de sal o incluso no utilizar sal en los alimentos.", 2),
            self._create_mc_challenge(u"Las grasas saturadas:", [u"Debemos consumirlas con precaución.", u"Mejoran nuestra salud cardiovascular.", u"Hay que consumirlas en exceso.", u"Las encontramos en la zanahoria.", u"Las encontramos en las frutas y verduras.", u"Se encuentran en la manzana."], u"Debemos consumirlas con precaución.", 3),
            self._create_mc_challenge(u"¿Qué conoces acerca de las grasas? Elije la opción verdadera.", [u"El colesterol LDL o “ malo “ es el colesterol que se acumula en las arterias y nos puede traer muchos problemas cardiovasculares. ", u"Si consumimos muchos alimentos ricos en colesterol nos volvemos más saludables.", u"El colesterol debe consumirse en exceso a diferencia de las frutas que se deben consumir en muy pocas cantidades.", u"Debemos tener una alimentación rica en grasas saturadas.", u"Las grasas saturadas se encuentran en la lechuga.", u"Las grasas saturadas se encuentran en el tomate."], u"El colesterol LDL o “ malo “ es el colesterol que se acumula en las arterias y nos puede traer muchos problemas cardiovasculares. ", 3),
            self._create_mc_challenge(u"Las grasas saturadas: ", [u"Deben consumirse pero con moderación.", u"Hay que consumirlas de forma libre sin importar la cantidad.", u"Son muy saludables para nuestra salud.", u"Son tan buenas como el ejercicio físico.", u"Son el alimento más nutritivo para nuestra salud.", u"Se encuentran en los duraznos."], u"Deben consumirse pero con moderación.", 3),
            self._create_mc_challenge(u"¿Cuál de estas opciones es la verdadera?", [u"La mayoría de los alimentos contienen naturalmente la cantidad de sal necesaria.", u"Es recomendable consumir alimentos fritos en vez de hervidos o al horno.", u"Es recomendable agregarle sal a los alimentos.", u"Al agregarle sal a los alimentos evitamos desarrollar hipertensión arterial.", u"Las verduras contienen muchas grasas saturadas.", u"Los fiambres y embutidos deben consumirse diariamente."], u"La mayoría de los alimentos contienen naturalmente la cantidad de sal necesaria.", 3),
            self._create_mc_challenge(u"¿Conoces los grupos de alimentos? Encuentra la opción correcta.", [u"El grupo de frutas y verduras incluye acelga, cebolla, espinaca, banana, manzana, tomate, zapallito, rabanito, morrón y muchas mas.", u"El grupo de azúcares y dulces incluye grasa vacuna, grasa de cerdo, manteca, margarina, aceites vegetales (arroz, girasol, oliva, maíz, soya) frutas secas.", u"El grupo de las grasas incluye azúcar, la miel, los dulces, mermeladas y frutas, dulce de leche y golosinas.", u"El grupo de las frutas y verduras incluye trigo, maíz, arroz, cebada, avena, centeno.", u"El grupo de las carnes incluye los dulces, mermeladas y frutas, dulce de leche y golosinas.", u"El grupo de las leches y derivados incluye harina de trigo, sémola, féculas, polenta, tapioca, gofio, panes, bizcochos, galletas, galletitas, pastas de todo tipo."], u"El grupo de frutas y verduras incluye acelga, cebolla, espinaca, banana, manzana, tomate, zapallito, rabanito, morrón y muchas mas.", 4),
            self._create_mc_challenge(u"¿Qué sabes en relación a las fibras en los alimentos?", [u"La fibra alimentaria nos ayuda a movilizar el intestino sin dificultad. ", u"La fibra alimentaria no regula funciones intestinales.", u"Si realizamos actividad física no movilizamos nuestro intestino sin dificultad.", u"El consumo de frutas no ayuda a movilizar nuestro intestino sin dificultad.", u"La fibra alimentaria no ayuda a  regular el colesterol en nuestro organismo.", u"El consumo de agua y de frutas y verduras no ayuda a que movilicemos el intestino sin dificultad."], u"La fibra alimentaria nos ayuda a movilizar el intestino sin dificultad. ", 4),
            self._create_mc_challenge(u"Las grasas saturadas:", [u"Se encuentran en la carne de cerdo.", u"Se encuentran en la naranja.", u"Se encuentran en las verduras.", u"Aumentan el colesterol bueno o HDL.", u"Son muy buenas para nuestra salud cardiovascular.", u"Debemos consumirlas todos los días en grandes cantidades."], u"Se encuentran en la carne de cerdo.", 4),
            self._create_mc_challenge(u"Debemos aumentar nuestra ingesta de agua cuando:", [u"Tenemos diarrea.", u"Nos reímos.", u"Leemos.", u"Jugamos con la computadora.", u"Jugamos a las cartas.", u"Escuchamos música."], u"Tenemos diarrea.", 5),
            self._create_mc_challenge(u"Los micronutrientes son:", [u"Las vitaminas y los minerales.", u"Los glúcidos o carbohidratos.", u"Los lípidos o grasas.", u"Las proteínas.", u"El asado.", u"El salame."], u"Las vitaminas y los minerales.", 5),
            self._create_mc_challenge(u"Acerca de los minerales:", [u"Si no consumimos alimentos ricos en hierro podremos padecer anemia.", u"La sal es fundamental y debemos agregarla en todos los alimentos. ", u"Los alimentos no  contienen sal en su forma natural.", u"Las lentejas los huevos y la carne no son alimentos ricos en hierro.", u"El bajo consumo de calcio en la dieta no nos provoca osteoporosis a largo plazo.", u"Nuestro organismo produce constantemente minerales por eso no es necesario consumirlos. "], u"Si no consumimos alimentos ricos en hierro podremos padecer anemia.", 5),
            self._create_mc_challenge(u"¿Qué consejo es el verdadero?", [u"Es importante para mantener la salud realizar  diariamente una alimentación variada que incluya alimentos de los seis grupos.  ", u"No es importante consumir diariamente en todas las  comidas verduras y frutas de estación.", u"No es importante controlar su consumo de carnes, fiambres, embutidos, manteca, margarina, mayonesa y frituras por su alto contenido en grasas.", u"No es importante disminuir el consumo de sal. ", u"Para rendir más durante el día  no es necesario comenzar  con un desayuno que incluya leche, pan y fruta.", u""], u"Es importante para mantener la salud realizar  diariamente una alimentación variada que incluya alimentos de los seis grupos.  ", 6),
            self._create_mc_challenge(u"Las proteínas son macronutrientes y las podemos encontrar en:", [u"Carnes y huevos ", u"Las golosinas", u"Refrescos", u"Manteca", u"Dulces", u"Chocolate"], u"Carnes y huevos ", 6),
            self._create_mc_challenge(u"¿Cuál de estos es un macronutriente? ", [u"Las proteínas.", u"Vitaminas.", u"Minerales.", u"La sal.", u"El flúor.", u"El calcio."], u"Las proteínas.", 6),
            self._create_mc_challenge(u"¿Acerca de las vitaminas, cuál es la opción verdadera?", [u"Son vitales para el organismo.", u"Las vitaminas son todas fabricadas por nuestro propio organismo.", u"Las vitaminas no son importantes.", u"La falta de vitaminas no nos produce enfermedades.", u"La cáscara de las frutas no contiene vitaminas.", u"Cocinar las frutas y verduras con una olla al vapor no nos conserva las vitaminas"], u"Son vitales para el organismo.", 7),
            self._create_mc_challenge(u"¿Cual de estos consejos de las guías GABA es el correcto?", [u"La alimentación debe ser variada e incluir alimentos de los 6 grupos.", u"Para rendir más durante el día debemos incluir un desayuno que incluya asado.", u"Comer sin importar las porciones indicadas en los grupos de alimentos.", u"Los lácteos no son necesarios en todas las edades.", u"Consumir una vez a la semana frutas de estación.", u"Aumentar el consumo de bebidas azucaradas."], u"La alimentación debe ser variada e incluir alimentos de los 6 grupos.", 7),
            self._create_mc_challenge(u"En relación a las vitaminas que se encuentran en frutas y verduras: ", [u"Se conservan mejor si consumo frutas y verduras con cáscara  porque muchas vitaminas se concentran en la cáscara.", u"Se conservan mejor  en las frutas y verduras si las hiervo durante un tiempo prolongado.", u"Se conservan mejor si las consumo fritas.", u"Las vitaminas no se encuentran en las frutas.", u"La vitamina A se encuentra en el tomate.", u"La vitamina A se encuentra en  el limón."], u"Se conservan mejor si consumo frutas y verduras con cáscara  porque muchas vitaminas se concentran en la cáscara.", 7),
            self._create_mc_challenge(u"Las fibras en la alimentación:", [u"Ayudan a regularizar nuestro tránsito intestinal junto al agua y el ejercicio.", u"No ayudan a movilizar nuestro intestino.", u"No son tan importantes.", u"Se encuentran en el asado.", u"Se encuentran en las golosinas.", u"No se encuentran en las frutas"], u"Ayudan a regularizar nuestro tránsito intestinal junto al agua y el ejercicio.", 8),
            self._create_mc_challenge(u"¿Cuál de estos consejos es el verdadero?", [u"Es importante incluir en el desayuno frutas.", u"No es necesario separar alimentos crudos de los cocidos", u"No es importante lavar los alimentos con agua y jabón.", u"No es necesario guardar la carne en la heladera.", u"Los niños deben consumir media fruta por día.", u"No es importante limpiar el lugar donde voy a cocinar."], u"Es importante incluir en el desayuno frutas.", 8),
            self._create_mc_challenge(u"¿Cuál de estos consejos de las guías GABA es el correcto?", [u"Controlar el consumo de carnes fiambres y embutidos.", u"Aumentar el consumo de sal.", u"Elegir los alimentos más caros.", u"No es importante cuidar la higiene de los alimentos.", u"Consumir muchas grasas saturadas.", u"Consumir mucha mayonesa."], u"Controlar el consumo de carnes fiambres y embutidos.", 8),
            self._create_mc_challenge(u"Acerca de los lácteos y derivados:", [u"El consumo de alimentos ricos en calcio como la leche y los quesos es muy importante para prevenir la osteoporosis.", u"La leche y los quesos son productos pobres en calcio.", u"El consumo de alimentos ricos en calcio no es importante.", u"Es necesario consumir alimentos ricos en calcio solo cuando somos niños.", u"Solo los adultos deben consumir alimentos ricos en calcio.", u"Solo los bebes deben consumir leche."], u"El consumo de alimentos ricos en calcio como la leche y los quesos es muy importante para prevenir la osteoporosis.", 9),
            self._create_mc_challenge(u"Acerca de la seguridad de los alimentos:", [u"La leche que consumimos debe ser pasteurizada y en caso de no serlo debemos hervirla para evitar la  gérmenes que pueden ser muy  perjudiciales.", u"Los huevos se pueden consumir poco cocidos o crudos porque son seguros.", u"Deberíamos consumir huevos poco cocidos y mayonesa casera.", u"La carne debe conservase fuera de la heladera.", u"Los alimentos crudos deben guardarse en el mismo recipiente que los cocidos.", u"Si tenemos animales no es necesario desparasitarlos si están lejos de la comida que vamos a consumir."], u"La leche que consumimos debe ser pasteurizada y en caso de no serlo debemos hervirla para evitar la  gérmenes que pueden ser muy  perjudiciales.", 9)                                                                               
        ]
        
        self.mc_challenges["spare_time"] = [
            self._create_mc_challenge(u"Es muy saludable:", [u"Tomar entre 2 y 3 litros de agua por día.", u"Trabajar y estudiar sin parar todo el día todos los días.", u"No controlarnos con el doctor para saber cómo estamos.", u"Exponernos al sol sin gorro. ", u"Comer muchos asados con mucha grasa.", u"No desayunar."], u"Tomar entre 2 y 3 litros de agua por día.", 1),
            self._create_mc_challenge(u"Es muy saludable:", [u"Bañarnos con agua y jabón todos los días.", u"Lavar nuestras manos una vez al día.", u"Cepillar  nuestros dientes una vez al día.", u"Realizarnos controles médicos una vez cada 10 años.", u"Cepillar nuestros dientes solo cuando comemos dulces.", u"Realizar actividad física una vez al mes."], u"Bañarnos con agua y jabón todos los días.", 1),
            self._create_mc_challenge(u"¿Cuántos horas de sueño promedio necesita un joven cada noche?", [u"8 horas", u"5 horas", u"6 horas", u"10 horas", u"11 horas", u"4 horas"], u"8 horas", 1),
            self._create_mc_challenge(u"¿Porque es importante descansar y dormir?", [u"Para recuperar energia.", u"Porque no tiene nada que hacer.", u"No se ve nada en la noche.", u"Porque durmiendo aprendemos la informacion de la escuela.", u"Para evitar la diarrea.", u"Para que nuestros músculos sean más fuertes."], u"Para recuperar energia.", 1),
            self._create_mc_challenge(u"Es importante practicar deporte (elige la mejor opción),:", [u"Para ejercitar el cuerpo, la digestión y evitar enfermedades cardiovasculares.", u"Para ganar, evitar enfermedades cardiovasculares y ser macho.", u"Para ser macho, dar la XO tiempo para cargar y ser musculoso.", u"Para evitar estreñimiento, inflar nuestros pulmones y eludir tareas domésticas.", u"Para evitar dolor de la panza, dormir mejor y ser más feliz.", u"Para quemar grasas corporales, dar a mi caballo tranquilidad y ser el mejor."], u"Para ejercitar el cuerpo, la digestión y evitar enfermedades cardiovasculares.", 1),
            self._create_mc_challenge(u"En mi tiempo libre es importante tener tiempo para jugar (elige la mejor opción),:", [u"Para desarrollar mi imaginación y es un derecho humano.", u"Es un derecho humano y para eludir tareas domésticas.", u"Es importante para dormir mejor y comer más.", u"Para que el día pase rápido y aprender sobre la vida.", u"Para olvidar la escuela y estar solo.", u"Para disfrutar con amigos y ser tramposo."], u"Para desarrollar mi imaginación y es un derecho humano.", 1),
            self._create_mc_challenge(u"Lo más importante de jugar deportes con amigos es (elige la mejor opción),:", [u"Jugar juntos.", u"Prevenir lesiones.", u"Ganar.", u"Ser muscoloso.", u"Para que los otros ganen.", u"Para ser popular."], u"Jugar juntos.", 1),
            self._create_mc_challenge(u"En mi tiempo de ocio se puede (elige la mejor opción),:", [u"Divertirse y desarrollarse personalmente.", u"Dormir mucho y comer todo el día.", u"Ver televisión y negar el ambiente social.", u"Aburrirse y quejarse.", u"Evitar las tareas escolares y domésticas.", u"Estar todo el día en la calle y hacer travesuras."], u"Divertirse y desarrollarse personalmente.", 1),
            self._create_mc_challenge(u"Está bien practicar deportes para evitar:", [u"Enfermedades cardiovasculares.", u"Las tareas de la escuela.", u"Mi familia.", u"Las tareas del campo.", u"Mis amigos.", u"Mis problemas."], u"Enfermedades cardiovasculares.", 1),
            self._create_mc_challenge(u"¿Qué actividad consume más energía corporal?", [u"Jugar fútbol.", u"Escribir una carta.", u"Jugar en la XO.", u"Pelar una manzana.", u"Escribir en el pizarró.n", u"Hacer un dibujo."], u"Jugar fútbol.", 1),
            self._create_mc_challenge(u"Durante el recreo lo más importante es (elige la mejor opción),:", [u"Disfrutar y jugar.", u"Pelear y jugar.", u"Quejarse y comer.", u"Hacer travesuras y molestar.", u"No hacer nada y beber refresco.", u"Jugar en la XO y gritar fuerte."], u"Disfrutar y jugar.", 1),
            self._create_mc_challenge(u"Es importante tener tiempo libre con mi familia (elige la mejor opción),:", [u"Para divertirse y hacer cosas juntos.", u"Para limpiar y hablar.", u"Para hablar y trabajar en el campo.", u"Para hacer nada y ver televisión.", u"Para divertirse y limpiar.", u"Para hacer asado y comer mucho."], u"Para divertirse y hacer cosas juntos.", 1),
            self._create_mc_challenge(u"Se debe ser responsable en su tiempo libre, para (elige la mejor opción),:", [u"Elegir las actividades que más me gustan.", u"Ganar trofeos.", u"Ser muy conocido.", u"No cuidar mi salud.", u"Evitar socializar con los otros.", u"Aburrirse mucho."], u"Elegir las actividades que más me gustan.", 1),
            self._create_mc_challenge(u"En el tiempo libre se disfruta leer para:", [u"Aprender y conocer más del mundo.", u"Evitar amigos y familia.", u"Crecer el conocimiento y comer mucho mientras se lee.", u"Evitar problemas escolares y personales.", u"Tener distracción y pasar el tiempo.", u"Estar adentro y no hacer tareas en el campo."], u"Aprender y conocer más del mundo.", 1),
            self._create_mc_challenge(u"Durante el juego está prohibido:", [u"Obligar a otros hacer lo que yo diga.", u"Ganar.", u"Escuchar al árbrito.", u"Aceptar las reglas.", u"Tomar agua.", u"Disfrutar."], u"Obligar a otros hacer lo que yo diga.", 1),
            self._create_mc_challenge(u"Durante el juego se tiene que respetar:", [u"Las reglas y los otros.", u"El egoísmo y el tiempo del juego.", u"Solo tus deseos y no el de los demás.", u"El tiempo del juego y no aceptar las variantes.", u"El ambiente donde se juega y dejar todo sucio.", u"Quebrar las reglas y hacer lo que quieren los demás."], u"Las reglas y los otros.", 1),
            self._create_mc_challenge(u"El ocio es:", [u"Una forma positiva de aprovechar el tiempo libre.", u"Una receta de cocina.", u"Una forma negativa para pasar el día.", u"Una forma de construir una casa.", u"Un derecho para mi mascota.", u"Una forma física."], u"Una forma positiva de aprovechar el tiempo libre.", 1),
            self._create_mc_challenge(u"No es ocio:", [u"Una forma de perder el tiempo.", u"Una manera divertirse.", u"Un tiempo para crear.", u"Un tiempo para jugar.", u"Un tiempo para disfrutar con otros.", u"Un tiempo para estar con la familia."], u"Una forma de perder el tiempo.", 1),
            self._create_mc_challenge(u"No es deporte:", [u"Trabajar en la huerta.", u"Saltar la cuerda.", u"Jugar al fútbol.", u"Correr.", u"Bailar.", u"Domar caballos."], u"Trabajar en la huerta.", 1),                           
        ]
        
        self.mc_challenges["responsability"] = [
            self._create_mc_challenge(u"Lo primero que debemos determinar para realizar nuestra huerta es:", [u"El terreno.", u"Que vamos a sembrar.", u"Como lo vamos a cercar.", u"Quien lo va a trabajar.", u"Como va a ser el riego.", u"Como protegerla del sol."], u"El terreno.", 1),
            self._create_mc_challenge(u"¿Cual es la parte más importante, trabajando en la huerta?", [u"Todas.", u"La siembra.", u"La elección de semillas.", u"La cosecha.", u"Separar las semillas.", u"El riego."], u"Todas.", 1),
            self._create_mc_challenge(u"Los controles en salud con el doctor sirven para:", [u"Aprender a cuidar de mi salud y prevenir enfermedades. ", u"Aprender matemáticas.", u"Aburrirme.", u"Aprender las tablas.", u"Perder el tiempo.", u"Aprender a leer."], u"Aprender a cuidar de mi salud y prevenir enfermedades. ", 1),
            self._create_mc_challenge(u"En relación a los controles en salud, ¿Cuál es la opción correcta?", [u"Todas las personas tienen derecho a  poder controlar su salud.", u"Sólo deben controlarse los bebés.", u"Sólo deben controlarse los niños.", u"Sólo deben controlarse los adultos.", u"Sólo deben controlarse los ancianos.", u"Sólo deben controlarse los escolares."], u"Todas las personas tienen derecho a  poder controlar su salud.", 1),
            self._create_mc_challenge(u"En relación a los controles en salud, ¿Cuál es la opción correcta?", [u"Los niños tienen derecho a que los adultos los lleven a controlar su salud. ", u"La frecuencia de controles en salud es igual para todas las edades.", u"En los controles en salud no aprendemos a cuidarnos y a alimentarnos correctamente.", u"Los controles en salud no son importantes.", u"Los controles en salud no me permiten aprender cosas acerca de mi salud.", u""], u"Los niños tienen derecho a que los adultos los lleven a controlar su salud. ", 1),
            self._create_mc_challenge(u"¿Cuándo debo concurrir al doctor?", [u"Debo concurrir al menos una vez por año a controlar mi salud. ", u"Únicamente cuando estoy enfermo.", u"Una vez  cada 5 años.", u"Una vez cada 2 años.", u"Sólo cuando me siento enfermo.", u"Sólo cuando me duele la cabeza."], u"Debo concurrir al menos una vez por año a controlar mi salud. ", 1),
            self._create_mc_challenge(u"Cuando voy a mis controles en salud es importante que el doctor revise:", [u"Mi peso.", u"Mi Xo.", u"Mis notas en la escuela.", u"Mi mascota.", u"Mi ropa.", u"Mis zapatos."], u"Mi peso.", 1),
            self._create_mc_challenge(u"¿Qué cuidados debo tener si vamos a nadar?", [u"Debemos siempre concurrir con un adulto.", u"Podemos ir solos y no importa que un adulto  nos acompañe.", u"Debemos nadar contra la corriente.", u"Si no se nadar es recomendable bañarme en lo hondo.", u"Si llevamos algo inflable para  jugar no es necesario atarlo. ", u"No hay que aprender cuidados para ir a nadar porque no es peligroso."], u"Debemos siempre concurrir con un adulto.", 1),
            self._create_mc_challenge(u"Acerca de las vacunas:", [u"Las vacunas son una importante barrera inmunológica que nos protegen de enfermedades.", u"No tiene importancia vacunarnos cuando ya somos niños grandes.", u"Tener un carné de vacunas no es importante.", u"El doctor en mis controles en salud no necesita saber si estoy correctamente vacunado.", u"Sólo los niños pequeños deben tener su carné de vacunas al día.", u"Si estoy sano no necesito vacunarme."], u"Las vacunas son una importante barrera inmunológica que nos protegen de enfermedades.", 1),
            self._create_mc_challenge(u"Si vamos a exponernos al sol, elije a la opción verdadera.", [u"Es recomendable que busquemos lugares de sombra. ", u"Es recomendable que vayamos de ropa oscura.", u"Es recomendable que llevemos poca agua.", u"No es necesario usar protector solar.", u"No es necesario usar lentes de sol.", u"La mejor hora para exponernos al sol es a  la una de la tarde."], u"Es recomendable que busquemos lugares de sombra. ", 1),
            self._create_mc_challenge(u"Acerca del agua:", [u"Si no se nadar es recomendable que no entre al agua.", u"No es recomendable que vayamos al agua solos.", u"Si se nadar no es importante que me acompañe un adulto al agua.", u"El fondo de los ríos y arroyos o lagos siempre es el mismo y no cambia nunca.", u"No es necesario atar los inflables que llevamos al agua.", u"Cuando vamos a nadar el agua debe llegar hasta nuestro cuello."], u"Si no se nadar es recomendable que no entre al agua.", 1),
            self._create_mc_challenge(u"Uno de los materiales fundamentales para la construcción de la huerta es:", [u"Pala ancha.", u"Escavadora.", u"Nylon.", u"Tractor.", u"Alambre.", u"Clavos."], u"Pala ancha.", 1),
            self._create_mc_challenge(u"Es conveniente que la huerta sea de forma:", [u"Rectangular.", u"Circular.", u"Triangular.", u"Hexagonal.", u"Piramidal.", u"Romboidal."], u"Rectangular.", 2),
            self._create_mc_challenge(u"¿Cuál de estos animales es enemigo de nuestras plantas?", [u"El pulgón.", u"El San Antonio Rojo.", u"La rana.", u"El sapo.", u"Las arañas.", u"Los murciélagos."], u"El pulgón.", 2),
            self._create_mc_challenge(u"En mis controles en salud:", [u"Debo controlar como veo y están mis ojos.", u"Debo controlar mis deberes.", u"Debo controlar mi carné escolar.", u"No es importante saber como esta mi altura.", u"No es importante saber cuanto peso.", u"No es importante pedir que me lleven a mis controles en salud."], u"Debo controlar como veo y están mis ojos.", 2),
            self._create_mc_challenge(u"¿Cuál de estas opciones es la verdadera?", [u"Todas las personas deben tener su carné de vacunas al día.", u"Las vacunas no influyen en nuestras defensas.", u"Recibir vacunas no es importante porque la buena alimentación ya nos aporta defensas.", u"Sólo los adultos deben vacunarse.", u"Las vacunas no son importantes.", u"Sólo los niños pequeños deben vacunarse."], u"Todas las personas deben tener su carné de vacunas al día.", 2),
            self._create_mc_challenge(u"Si vamos a exponernos al sol, elije a la opción verdadera.", [u"El gorro recomendable para estar al sol debería ser de ala ancha, que proteja orejas, cara y cuello.", u"Los rayos UV solo dañan nuestra piel y no otras partes de nuestro organismo.", u"Si vamos a exponernos al sol debemos usar gorro sin visera.", u"Es recomendable que la ropa que usemos sea blanca.", u"No es importante consultar al doctor si me encuentro un lunar sospechoso en mi piel.", u"El exámen de mi piel no es importante cuando voy a mis controles médicos."], u"El gorro recomendable para estar al sol debería ser de ala ancha, que proteja orejas, cara y cuello.", 3),
            self._create_mc_challenge(u"Para estar seguros cuando vamos al agua debemos hacer pie y además:", [u"El agua debe llegarnos hasta la cintura.", u"El agua debe llegarnos hasta los labios.", u"El agua debe llegarnos hasta los tobillos.", u"El agua debe llegarnos hasta las rodillas.", u"El agua debe llegarnos hasta el cuello.", u"El agua debe llegarnos hasta la nariz."], u"El agua debe llegarnos hasta la cintura.", 3),
            self._create_mc_challenge(u"Uno de los métodos de siembra en nuestra huerta es:", [u"El directo.", u"En línea", u"Al voleo", u"En casilla", u"En un hueco.", u"Hidroponia."], u"El directo.", 3),
            self._create_mc_challenge(u"Es más fácil cuidar de las semillas sembrando:", [u"En almácigos.", u"Directamente en la tierra.", u"Al voleo.", u"En línea.", u"En casillas o hueco.", u"En agua."], u"En almácigos.", 3),
            self._create_mc_challenge(u"Los canteros deben estar:", [u"Un poco por arriba del nivel del suelo.", u"15 cms. por debajo del nivel del suelo.", u"1 metro arriba del nivel del suelo.", u"A ras del suelo.", u"a 1 metro de profundidad.", u"a 50 cms de profundidad."], u"Un poco por arriba del nivel del suelo.", 4),
            self._create_mc_challenge(u"Acerca de mis derechos y obligaciones en relación a mi salud marque la opción verdadera.", [u"En la escuela puedo ayudar a los más pequeños a aprender a cepillar sus dientes.", u"No es importante ser responsable a la hora de exponernos al sol.", u"Cuando vamos a nadar debemos ir solos sin un adulto que nos acompañe.", u"No es importante enseñar a mi familia y mis compañeros hábitos saludables a cerca de nuestra salud.", u"Estar vacunados con las vacunas obligatorias no es importante.", u"Los únicos que deben vacunarse son los niños pequeños."], u"En la escuela puedo ayudar a los más pequeños a aprender a cepillar sus dientes.", 4),
            self._create_mc_challenge(u"¿Cuáles son los horarios recomendados para exponernos al sol en verano?", [u"Antes de las 11:00 o después de las 17:00. ", u"A las 12:00 horas.", u"A las 16:00 horas.", u"A las 13:00 horas.", u"A las 15:00 horas", u"A las 14:00 horas."], u"Antes de las 11:00 o después de las 17:00. ", 4),
            self._create_mc_challenge(u"La orientación de las camas altas o canteros debe ser:", [u"Norte-Sur.", u"Este-Oeste.", u"Sur-Este.", u"Norte-Oeste.", u"Sur-Oeste.", u"Este-Norte."], u"Norte-Sur.", 4),
            self._create_mc_challenge(u"Ante la presencia de plagas debemos usar:", [u"Productos no tóxicos.", u"Agroquímicos.", u"Fuego.", u"Hipoclorito de sodio.", u"Detergente.", u"Alcohol."], u"Productos no tóxicos.", 5),
            self._create_mc_challenge(u"¿Cuál de estos pasos no es parte de la construcción de una huerta?", [u"Colocar las semillas.", u"Clavar las estacas en cada una de las esquinas del lugar elegido.", u"Limpiar la superficie, sacando piedras, vidrios y basura.", u"Marcar las camas altas.", u"Sacar la tierra de las camas altas con una profundidad de 15 a 30 cms.", u"Remover el fondo del cantero y rellenar con materia orgánica."], u"Colocar las semillas.", 5),
            self._create_mc_challenge(u"Las camas altas o canteros en una huerta, alcanzan un largo de:", [u"6 a 15 mts.", u"1 a 5 mts.", u"6 a 15 cms.", u"15 a 60 mts.", u"6 a 50 mts.", u"1 a 50 mts."], u"6 a 15 mts.", 5),
            self._create_mc_challenge(u"El humus de lombriz se obtiene ulilizando lombrices para digerir:", [u"Materia orgánica.", u"Materia inorgánica.", u"Sólo de excremento de animales.", u"Restos pino o eucaliptus.", u"Plásticos y vidrios.", u"Todos los residuos de la cocina."], u"Materia orgánica.", 5),
            self._create_mc_challenge(u"Para retirar el humus del lumbricario se debe:", [u"Separar las lombrices con trampas.", u"Esperar a que las lombrices se vayan solas.", u"Pasar el humus por filtros para atrapar las lombrices.", u"Poner productos para que la lombriz salga.", u"Mojar para espantar a las lombrices.", u"Quitar las lombrices con humo."], u"Separar las lombrices con trampas.", 6),
            self._create_mc_challenge(u"¿Qué recomendaciones deberíamos cumplir cuando vamos a exponernos al sol?", [u"Usar protector solar. ", u"Vestirnos con ropa blanca.", u"Tomar poco agua.", u"No es necesario usar gorro. ", u"Tomar sol a las 12 del mediodía.", u"No es necesario buscar lugares de sombra."], u"Usar protector solar. ", 6),
            self._create_mc_challenge(u"¿Cuál de estas plantas se puede plantar con la arveja?", [u"Zanahoria.", u"Cebolla.", u"Ajo.", u"Papa.", u"Gladiolos.", u"Pino."], u"Zanahoria.", 6),
            self._create_mc_challenge(u"Los canteros se deben realizar de la siguiente manera:", [u"Separados por 50 cms.", u"Uno al lado del otro.", u"Separados por 6 metros.", u"Separados por 6 centímetros.", u"Sin separación.", u"A menos de 10 centímetros entre si."], u"Separados por 50 cms.", 6),
            self._create_mc_challenge(u"Acerca de mis derechos y obligaciones en relación a mi salud marque la opción verdadera.", [u"Todos los niños tenemos derecho a que los adultos responsables nos lleven a nuestros controles en salud.", u"Aprender a practicar hábitos saludables no es importante.", u"No es necesario que visite a mi doctor si no estoy viendo bien con mis ojos.", u"El olvidarme de mis controles en salud con el doctor no tiene importancia.", u"En mis controles en salud con el doctor el control de mi peso y de mi altura no son importantes.", u"En mis controles en salud con el doctor no es importante que valoren como ven mis ojos."], u"Todos los niños tenemos derecho a que los adultos responsables nos lleven a nuestros controles en salud.", 7),
            self._create_mc_challenge(u"Cuando vamos a nadar a ríos o arroyos es importante:", [u"No nadar en contra de la corriente pues podemos cansarnos.  ", u"Tirarnos al agua aunque no sepamos nadar.", u"Comer antes de ir.", u"No llevar gorro", u"Llevar alcohol.", u"Ir solos."], u"No nadar en contra de la corriente pues podemos cansarnos.  ", 7),
            self._create_mc_challenge(u"¿Que planta no es conveniente plantar con el pepino?", [u"Papa", u"Girasol.", u"Porotos.", u"Maíz.", u"Arvejas.", u"Rabanito."], u"Papa", 7),
            self._create_mc_challenge(u"Cuando se usan agroquímicos: ", [u"No debemos mezclar la ropa contaminada con agroquímicos con ropa limpia.", u"No es importante usar ropa de protección específica para esa actividad.", u"Luego de haberlos aplicado no es importante colgar en ambiente ventilado la vestimenta utilizada durante la aplicación.", u"No es necesario ducharse con abundante agua y jabón.", u"No es importante lavar la ropa contaminada con abundante agua y jabón.", u"No es necesario utilizar guantes durante el lavado de la ropa contaminada."], u"No debemos mezclar la ropa contaminada con agroquímicos con ropa limpia.", 7),
            self._create_mc_challenge(u"¿Cuáles de estos síntomas deben tenerse en cuenta cuando usamos agroquímicos y consultar inmediatamente?.", [u"Dificultad para respirar o falta de aire", u"Risa.", u"Ganas de tomar un helado.", u"Ganas de leer.", u"Ganas de jugar a la Xo.", u"Ganas de ir a la escuela."], u"Dificultad para respirar o falta de aire", 8),
            self._create_mc_challenge(u"¿Cuál de estas plantas no se lleva bien con el resto de la lista?", [u"La Papa.", u"La Cebolla.", u"La Zanahoria.", u"La Menta.", u"La Ortiga.", u"La Borraja."], u"La Papa.", 8),
            self._create_mc_challenge(u"¿Cuál de estos pasos no es necesario para comer alimentos crudos de la huerta?", [u"Hervir el alimento.", u"Potabilizar el agua en caso que no lo sea.", u"Sacar las partes en mal estado.", u"Eliminar restos de tierra con abundante agua potable.", u"Dejar en remojo 15 minutos con agua e hipoclorito. ", u"Enjuagar nuevamente con abundante agua potable."], u"Hervir el alimento.", 8),
            self._create_mc_challenge(u"¿Qué conoces acerca de los cuidados del sol?", [u"El sol emite radiaciones UV que pueden dañar seriamente nuestra piel.", u"El sol es recomendable a todas las horas del día.", u"El sol puede dañarnos más con ropa oscura que con ropa clara.", u"El sol es recomendable a las 2 de la tarde.", u"No es importante usar gorro cuando vamos a exponernos al sol.", u"No es necesario tomar agua cuando estoy al sol."], u"El sol emite radiaciones UV que pueden dañar seriamente nuestra piel.", 8),
            self._create_mc_challenge(u"En relación a los cuidados del sol:", [u"La piel de los niños es más fina y más propensa a sufrir los daños del sol a edades muy tempranas. ", u"Es recomendable exponernos entre las 11 y las 17 horas.", u"Cuando vamos a exponernos al sol es importante usar ropa clara.", u"No es importante usar pantalla solar para protegernos del sol.", u"Los lentes de sol no son importantes porque los rayos Uv no dañan los ojos. ", u"Los lentes de sol solo deben ser usados por niños."], u"La piel de los niños es más fina y más propensa a sufrir los daños del sol a edades muy tempranas. ", 9),
            self._create_mc_challenge(u"¿Cuál de estas recomendaciones es la correcta? ", [u"Los niveles de profundidad en arroyos, bañados, y lagos, cambian constantemente en función de los fenómenos climáticos.", u"Cuando vamos a estar al sol es recomendable usar ropa bien clara. ", u"Es recomendable no tomar abundante agua. ", u"Concurrir solos sin un adulto.", u"Tratar de comer por lo menos 15 min antes de ir a nadar.", u"Meternos al agua si no sabemos nadar."], u"Los niveles de profundidad en arroyos, bañados, y lagos, cambian constantemente en función de los fenómenos climáticos.", 9),
            self._create_mc_challenge(u"¿Qué recomendaciones debo conocer sobre los agroquímicos?", [u"No fumar, comer, ni beber durante la manipulación de agroquímicos. ", u"No es importante usar ropa de protección específica para usar agroquímicos. ", u"Colgar en un ambiente ventilado la vestimenta de protección utilizada durante la aplicación no es importante.", u"No es necesario lavar la ropa contaminada con abundante agua y jabón. ", u"En caso de haber tenido contacto con una sustancia química, y tener algún síntoma como falta de aire, no es importante consultar al médico. ", u"La correcta higiene de alimentos no es importante para evitar la contaminación con agroquímicos."], u"No fumar, comer, ni beber durante la manipulación de agroquímicos. ", 9)      
        ]
        
        #######################################################################
        
        
        
        # True or false
        # 0 = False | 1 = True
        
        self.tf_challenges = {}
        
        # Physica
        self.tf_challenges["physica"] = [
            self._create_tf_challenge(_("La alimentación adecuada previene muchas enfermedades \nimportantes"), 1, 10, 10),
            self._create_tf_challenge(_("Si no nos vacunamos con las vacunas obligatorias podemos \nenfermarnos"), 1, 10, 10),
            self._create_tf_challenge(_("Cuando estamos ingiriendo alimentos en menor proporción \na lo que necesitamos, podemos volvernos más \nsusceptibles a las infecciones "), 1, 10, 10),
        ]
        
        # Hygiene
        self.tf_challenges["hygiene"] = [
            self._create_tf_challenge(_("Muchos alimentos pueden estar contaminados con agroquímicos, \ny pesticidas porque son frecuentemente usados"), 1, 10, 10),
            self._create_tf_challenge(_("Si no voy a comer no necesito lavarme las manos "), 0, 10, 10),
            self._create_tf_challenge(_("Lo primero que hay que hay que hacer cuando vamos a lavarnos \nlas manos es ponernos jabón"), 0, 10, 10),
        ]
        
        # Nutrition
        self.tf_challenges["nutrition"] = [
            self._create_tf_challenge(_("Cuando aprendemos hábitos saludables estamos cuidando nuestra \nsalud"), 1, 10, 10),
            self._create_tf_challenge(_("Tomar mucha agua, hacer ejercicio y comer frutas y verduras \nayuda a mover el intestino sin dificultad"), 1, 10, 10),
            self._create_tf_challenge(_("El desayuno no es importante en nuestra alimentación"), 0, 10, 10),
        ]
        
        # Spare time
        self.tf_challenges["spare_time"] = [
            self._create_tf_challenge(_("La actividad física mejora nuestra imagen"), 1, 10, 10),
            self._create_tf_challenge(_("La actividad física  no nos ayuda prevenir enfermedades \ncomo el sobrepeso y la obesidad "), 0, 10, 10),
            self._create_tf_challenge(_("Ser sedentarios no tiene importancia y no afecta nuestra \nsalud"), 0, 10, 10),
        ]
        
        # Responsability
        self.tf_challenges["responsability"] = [
            self._create_tf_challenge(_("Hay que hacer los deberes en la escuela"), 1, 10, 10),
            self._create_tf_challenge(_("Es bueno ayudar en las tareas domésticas"), 0, 10, 10),
        ]
    
    def _create_mc_challenge(self, question, answers, correct_answer, level, image=None):
        """
        Create a new mc_challenge (tuple)
        """
        challenge = (question, answers, correct_answer, level, image)
        return challenge
        
    def _create_tf_challenge(self, question, correct_answer, win_points, lose_points, image=None):
        """
        Create a new tf_challenge (tuple)
        """
        challenge = (question, [_("False"), _("True")], correct_answer, win_points, lose_points, image)
        return challenge
    
    def get_challenge(self, kind):
        """
        Load and return a random "created" mc_challenge
        """
        if kind == "mc":
            
            bar = self.game_man.get_lowest_bar()
            
            challenges = self.mc_challenges[bar.id]
            
            r = random.randrange(0, len(challenges))
            c = challenges[r]
            
            # Set challenge attributes
            self.mc_challenge.set_question(c[0])
            self.mc_challenge.set_correct_answer(c[2])
            self.mc_challenge.set_answers(c[1])
            
            # If challenge has an image
            if c[4]:
                self.mc_challenge.set_image(c[4])
                
            return self.mc_challenge
            
        elif kind == "tf":
            self.tf_challenge.kind = "normal"
            bar = self.game_man.get_lowest_bar()
            
            challenges = self.tf_challenges[bar.id]
            
            r = random.randrange(0, len(challenges))
            c = challenges[r]
            
            # Set challenge attributes
            self.tf_challenge.set_question(c[0])
            self.tf_challenge.set_correct_answer(c[2])
            self.tf_challenge.set_answers(c[1])
            self.tf_challenge.set_win_points(c[3])
            self.tf_challenge.set_lose_points(c[4])
            
            # If challenge has an image
            if c[5]:
                self.tf_challenge.set_image(c[5])
                
            return self.tf_challenge
                
        elif kind == "master":
            self.tf_challenge.kind = "master"
            
            l = random.randrange(0, 5)
            challenges = self.mc_challenges[self.mc_challenges.keys()[l]]
            
            r = random.randrange(0, len(challenges))
            c = challenges[r]
            
            # Set challenge attributes
            self.tf_challenge.set_question(c[0])
            self.tf_challenge.set_correct_answer(c[2])
            self.tf_challenge.set_answers(c[1])            
            
            # If challenge has an image
            if c[4]:
                self.tf_challenge.set_image(c[4])
                
            return self.tf_challenge
